"""
Django settings for botService project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bif#zx5)5@0jod5sdob)ovxryl_fz9igv&i43vb^a%d67%c%m&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'ali-server.july-aic.site',
    '127.0.0.1', '0.0.0.0',
    '19de-47-254-200-31.ngrok.io',
    '47.254.200.31',
    # 'ec2-18-219-74-127.us-east-2.compute.amazonaws.com',
    # 'test-01.clinker.vip', # Product Env.
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'chatterbot.ext.django_chatterbot',
    'linebot.apps.LinebotConfig',
    # 'chatbot.respondent.Respondent',
    # 'chatbot.trainer.BotTrainer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'chatbot.respondent.Respondent',
    # 'chatbot.trainer.BotTrainer',
    # 'chatterbot.ChatBot',
    # 'chatbot.respondent',
    # 'chatbot.trainer',
]

# MIDDLEWARE_CLASSES = [
#     'chatbot.respondent.Respondent',
#     'chatbot.trainer.BotTrainer',
# ]

ROOT_URLCONF = 'botService.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'botService.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Author: Darren K.J. Chen
# E-mail: kjchen@protonmail.ch

LINE_CHANNEL = {
    'ACCESS_TOKEN': [
        'pmFK0WuqMRluEOjfSB1Hhm5Iw/0teY3uHgn7OMucGCGgA7e3DGAxQ0lueixtaLeydnZfkwqOaC1kIMErKgqyxrvS1PNp61MLakb8odjUzJJMjFm8QH17TRsAMfeiZr3bRfJsPqJDk/mbysnq6XCgMQdB04t89/1O/w1cDnyilFU=',
        # 'AaRqIBPWc6QDPaG4cfFQs7hMYBqOcDtuDVyPEpQxmPAHphDC1yLoefJi6pT4r7VU/LmSMO5rCeRC3SLr3vrz0ai9EAZSzPdVcW4qsrE5VpNbaBQS+7J2PJhIURAJyir7mtG40FPP5XGh3zG+9ryFgQdB04t89/1O/w1cDnyilFU=',
        # 'xjdfStSUdYn1bWtchEhUjVW7c+EIHgEth3+sOyfAuKIS540DETT9mcJxuVw8TD+CiDyT1VEKI+D7DcR5rwpY0/alFazT92zy8iozHkUENliBlaShXTwP3rpRwcnjpAipdYDJBAUITzKwAxg580dU/AdB04t89/1O/w1cDnyilFU=',
    ], 'SECRET': [
        '7532fe88dc60813138092e2186bdea5d',
        # '691b43a53b645557d433d27834fa8309',
        # 'eeecdf0ebc327ba7caa16b0ec800417f',
    ]
}

FAMILY_GROUP = [
    'Cf7bb5c05288433dae62584999121acd0',
    'C03af024ed8c1096ee920cfaa834fefb5'
]

NEW_TIME = '22:22'

# LINE_CHANNEL_ACCESS_TOKEN = 'xjdfStSUdYn1bWtchEhUjVW7c+EIHgEth3+sOyfAuKIS540DETT9mcJxuVw8TD+CiDyT1VEKI+D7DcR5rwpY0/alFazT92zy8iozHkUENliBlaShXTwP3rpRwcnjpAipdYDJBAUITzKwAxg580dU/AdB04t89/1O/w1cDnyilFU='
# LINE_CHANNEL_SECRET = 'eeecdf0ebc327ba7caa16b0ec800417f'

# IS_TRAINING = [
#     False,
#     False,
# ]

# CONVERSATION_PATH = [
#     '/home/ubuntu/reas_bot/BotService/botService/chatbot/corpus/conversation_00.json',
#     '/home/ubuntu/reas_bot/BotService/botService/chatbot/corpus/conversation_01.json',
# ]

# CONSECUTIVE_TIMES = [
#     0,
#     0,
# ]
#
# BOT_CONF = [
#     {
#         'botName': 'BOT_00',
#         'conversationName': 'conversations',
#         'clientQuestion': 'DefalutQuestion',
#         'clientAnswer': 'DefalutAnswer',
#         'QnA': list(),
#         'trainedMsg': list(),
#         'allConversation': dict(),
#         'logic_adapters': [
#             "chatterbot.logic.BestMatch"
#         ]
#     }, {
#         'botName': 'BOT_01',
#         'conversationName': 'conversations',
#         'clientQuestion': 'DefalutQuestion',
#         'clientAnswer': 'DefalutAnswer',
#         'QnA': list(),
#         'trainedMsg': list(),
#         'allConversation': dict(),
#         'logic_adapters': [
#             "chatterbot.logic.BestMatch"
#         ]
#     },
# ]

OPEN_WEATHER_DATA_TOKEN = 'CWB-D7E87A9F-817D-4DB6-AFCD-84F8A67A3F38'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL  = '/conf/'
STATIC_ROOT = '/root/EldersGreetingBot/botService/conf/'
